version: '3'

services:

  love_paws_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - love-paws-network

networks:

  love-paws-network:
    driver: bridge
    